language: ruby
rvm:
  - 2.2.1

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER travis_ci_test WITH PASSWORD 'postgres';" -U postgres

script:
  - export RAILS_ENV=test
  - bundle exec rake db:setup
  - bundle exec rake db:test:prepare
